# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        id: create-release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"

  perform-release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GraalVM (Java 21)
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: '21'
          cache: gradle

      - name: Install native-image
        run: gu install native-image
        shell: pwsh

      - name: Set up MSVC dev prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Gradle cache (extra)
        uses: actions/cache@v4
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/graalvm/**
          asset_name: pack.zip
          asset_content_type: application/zip
